# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
locale: en-US
title: Shaohang Wei
my_site_title: Shaohang Wei
name: Shaohang Wei
description: "weish[at]buaa.edu"
baseurl: #/blog # the subpath of your site, e.g. "/blog"
#url: http://127.0.0.1:4000
url: https://sylvain-wei.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: /images/shaohangwei2.jpg # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 200 # 200
markdown: kramdown
mathjax: true # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro" # TODO: 普通的无衬线英文
    weights: "400,400i,700,700i"
  - name: "Lora"            # TODO: 衬线字体
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: weish # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: veison02 # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search TODO: if searching is too slow, then set it to 'false'
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Shaohang Wei
  picture:
  email: weish@buaa.edu.cn
  twitter: veison02
  # facebook: zi.lin.12935
  github: sylvain-wei
  links:
    - title: GitHub
      url: https://github.com/sylvain-wei
      icon: fa-brands fa-github
    - title: Twitter
      url: https://twitter.com/veison02
      icon: fa-brands fa-twitter
    - title: Instagram
      url: https://www.instagram.com/sylvain_1006
      icon: fa-brands fa-instagram
    - title: Zhihu
      url: https://www.zhihu.com/people/sylvain02
      icon: fa-brands fa-zhihu
    - title: Email
      url: https://weish@buaa.edu.cn
      icon: fa-solid fa-at

# Footer Links
# See https://fontawesome.com/v6/search?q=email&o=r
footer_links:
  - title: GitHub
    url: https://github.com/sylvain-wei
    icon: fa-brands fa-github
  - title: Twitter
    url: https://twitter.com/veison02
    icon: fa-brands fa-twitter
  - title: Instagram
    url: https://www.instagram.com/sylvain_1006
    icon: fa-brands fa-instagram
  - title: Zhihu
    url: https://www.zhihu.com/people/sylvain02
    icon: fa-brands fa-zhihu
  - title: Email
    url: https://weish@buaa.edu.cn
    icon: fa-solid fa-at
  # - title: Feed
  #   url: atom.xml
  #   icon: fa-solid fa-rss

  # - title: Linkedin
  #   url: https://www.linkedin.com/in/zi-lin/
  #   icon: fab fa-linkedin
