remote_theme: ankitsultana/researcher
plugins:
  - jekyll-remote-theme
title: Shaohang Wei
url: "https://sylvain-wei.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 # - name: "Resume"
   # link: "resume.pdf"
 # - name: "Contact"
   # link: "contact"
